package server.game.players.packets.commands;

import java.util.function.BiPredicate;

import org.Vote.MainLoader;

import server.Config;
import server.Connection;
import server.Server;
import server.game.content.ItemSpawnSearch;
import server.game.content.PlayerOwnedShop;
import server.game.npcs.WorldAdventurer;
import server.game.players.Client;
import server.game.players.PlayerHandler;
import server.game.players.packets.Commands;
import core.util.Misc;
import core.util.rspswebstore;

/**
 * Commands any player may use, lifted from the un-gated head of the old chain.
 *
 * Generated by build/purge/gen-command-registry.js. Do not edit by hand.
 */
final class GeneralCommands {

	private GeneralCommands() {
	}

	static void register() {
		CommandHandler.register(Command.where(0, Integer.MAX_VALUE, (c, playerCommand) ->
				playerCommand.startsWith("bsearch") && c.isBanking,
				(c, playerCommand) -> {
				String term = playerCommand.length() > 8 ? playerCommand.substring(8).trim() : "";
				c.getBank().applySearch(term);
		}));

		CommandHandler.register(Command.exact("banki", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				if(c.isBanking) {
					c.getItems().bankInventory();
					c.sendMessage("Inventory successfully banked.");
				}
		}));

		CommandHandler.register(Command.exact("banke", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				if(c.isBanking) {
					c.getItems().bankEquipment();
				         	c.sendMessage("Equipment successfully banked.");
				}
		}));

		CommandHandler.register(Command.exact("players", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				c.sendMessage("Current amount of players online: @red@"
						+ PlayerHandler.getPlayerCount() + "@bla@!");
		}));

		CommandHandler.register(Command.exact("cancel", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				if (c.itemSpawnSearching) {
					c.itemSpawnSearching = false;
					c.sendMessage("Item search cancelled.");
				} else if (c.posSearchingItem || c.posSearchingPlayer) {
					c.posSearchingItem = false;
					c.posSearchingPlayer = false;
					c.sendMessage("Search cancelled.");
				} else {
					c.sendMessage("No search in progress to cancel.");
				}
		}));

		CommandHandler.register(Command.prefix("help", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				c.sendMessage("You have submitted your help ticket, please wait for a staff member to reply.");
				for (int j = 0; j < PlayerHandler.players.length; j++) {
					if (PlayerHandler.players[j] != null) {
						if(PlayerHandler.players[j].playerRights > 0) {
							Client staff = (Client)PlayerHandler.players[j];
							staff.sendMessage(Misc.capitalize(c.playerName)+ " is requesting assistance!");
						}
					}
				}
		}));

		CommandHandler.register(Command.where(0, Integer.MAX_VALUE, (c, playerCommand) ->
				playerCommand.equalsIgnoreCase("claimweb") || playerCommand.equalsIgnoreCase("donated"),
				(c, playerCommand) -> {
				int returnval = rspswebstore.checkwebstore(c, c.playerName);
				String returnv = Integer.toString(returnval);

				 switch(returnv) {
				 default:
					 c.sendMessage("Your donation was not found.");
					 break;
				 }
		}));

		CommandHandler.register(Command.where(0, Integer.MAX_VALUE, (c, playerCommand) ->
				playerCommand.equalsIgnoreCase("claim") || playerCommand.equalsIgnoreCase("check") || playerCommand.equalsIgnoreCase("reward") || playerCommand.equalsIgnoreCase("voted"),
				(c, playerCommand) -> {
				    try {
				        org.Vote.VoteReward reward = MainLoader.hasVoted(c.playerName.replaceAll(" ", "_"));
				        if(reward != null){
				            switch(reward.getReward()){
				                case 0:
				                	c.votePoints += 2;
				                	c.getPA().sendFrame126("@red@[@or1@Vote@red@] Points: @or2@"+c.votePoints, 7339);
				                	c.sendMessage("2 vote points added to your account. Check the quest tab.");
				                    break;
				                case 1:
				                	c.getItems().addItem(995, 2000000);
				                	break;

				                default:
				                    c.sendMessage("Reward not found.");
				                    break;
				            }
				for (int j = 0; j < PlayerHandler.players.length; j++) {
					if (PlayerHandler.players[j] != null) {
						Client c2 = (Client)PlayerHandler.players[j];
						c2.sendMessage("@cr1@@red@[Vote] @dre@"+c.playerName+" just voted for "+Config.SERVER_NAME+"!");
					}
				}
				        } else {
				            c.sendMessage("You have no items waiting for you.");
				        }
				    } catch (Exception e){
				        c.sendMessage("[GTL Vote] A SQL error has occured.");
				    }
		}));

		CommandHandler.register(Command.prefix("donate", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				c.getPA().sendFrame126("", 12000);
		}));

		CommandHandler.register(Command.prefix("forums", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				c.getPA().sendFrame126("www." + Config.FORUMS + "/forums", 12000);
		}));

		CommandHandler.register(Command.prefix("vote", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				c.getPA().sendFrame126("www." + Config.FORUMS + "/vote", 12000);
		}));

		CommandHandler.register(Command.prefix("train", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				c.getPA().spellTeleport(2670, 3712, 0);
		}));

		CommandHandler.register(Command.where(0, Integer.MAX_VALUE, (c, playerCommand) ->
				playerCommand.equalsIgnoreCase("max") || playerCommand.equalsIgnoreCase("adventurer"),
				(c, playerCommand) -> {
				WorldAdventurer.teleportTo(c);
		}));

		CommandHandler.register(Command.prefix("commands", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				c.sendMessage("::train ::max/::adventurer ::players ::help ::reward/::check/::voted ::forums ::vote ::donate");
				c.sendMessage("::changepass *pass here* ::yell ::banki ::banke ::donated/::claimweb");
				c.sendMessage("--- Player Owned Shop ---");
				c.sendMessage("::pos - Opens your player owned shop");
				c.sendMessage("::possearch playerName - Search a player's shop");
		}));

		CommandHandler.register(Command.exact("pos", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				c.getPA().openPlayerOwnedShop();
		}));

		CommandHandler.register(Command.prefix("shop", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				c.getPA().showInterface(50000);
				c.sendMessage("Opening custom Shop Interface (ID: 50000)");
		}));

		CommandHandler.register(Command.prefix("possearch", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				try {
					String name = playerCommand.substring(9).trim();
					if (name.length() > 0) {
						c.getPA().searchPOSByPlayer(name);
					}
				} catch (Exception e) {
					c.sendMessage("Usage: ::possearch playerName");
				}
		}));

		CommandHandler.register(Command.where(0, Integer.MAX_VALUE, (c, playerCommand) ->
				playerCommand.equalsIgnoreCase("spawnfakeshops") && c.playerRights >= 2,
				(c, playerCommand) -> {
				PlayerOwnedShop.generateFakeListings();
				c.sendMessage("Generated test shop listings.");
		}));

		CommandHandler.register(Command.prefix("searchitem", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				try {
					int itemId = Integer.parseInt(playerCommand.substring(10).trim());
					c.getPA().searchPOSByItem(itemId);
				} catch (Exception e) {
					c.sendMessage("Usage: ::searchitem [itemId]");
				}
		}));

		CommandHandler.register(Command.prefix("searchplayer", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				try {
					String playerName = playerCommand.substring(12).trim();
					if (playerName.length() > 0) {
						c.getPA().searchPOSByPlayer(playerName);
					} else {
						c.sendMessage("Usage: ::searchplayer [playerName]");
					}
				} catch (Exception e) {
					c.sendMessage("Usage: ::searchplayer [playerName]");
				}
		}));

		CommandHandler.register(Command.where(0, Integer.MAX_VALUE, (c, playerCommand) ->
				playerCommand.startsWith("changepass") && playerCommand.length() > 11,
				(c, playerCommand) -> {
				c.playerPass = playerCommand.substring(11);
				c.sendMessage("Your password is now: @red@" + c.playerPass);
		}));

		CommandHandler.register(Command.prefix("yell", 0, Integer.MAX_VALUE, (c, playerCommand) -> {
				for (int j = 0; j < PlayerHandler.players.length; j++) {
					if (PlayerHandler.players[j] != null) {
						Client c2 = (Client)PlayerHandler.players[j];
						if (c.playerRights == 0) {//comment this out later
							c.sendMessage("You need to be a donator do do this.");
							//c2.sendMessage("@dbl@" + Misc.capitalize(c.playerName) +": " + Misc.optimizeText(playerCommand.substring(5)) +" ");
						}
						if (c.playerRights == 1) {
							c2.sendMessage("[Moderator] @cr1@@or3@" +  Misc.capitalize(c.playerName) +": <col=424242>" + Misc.optimizeText(playerCommand.substring(5)) +"</col>");
						}
						if (c.playerRights == 2) {
							c2.sendMessage("[Administrator] @cr2@@or3@" +   Misc.capitalize(c.playerName) +": <col=013ADF>" + Misc.optimizeText(playerCommand.substring(5)) +"</col>");
						}
						if (c.playerRights == 3) {
							c2.sendMessage("[Owner] @cr2@@or3@" +   Misc.capitalize(c.playerName) +": <col=013ADF>" + Misc.optimizeText(playerCommand.substring(5)) +"</col>");
						}
						if (c.playerRights == 4) {
							c2.sendMessage("[Donator] @cr3@@or3@" +   Misc.capitalize(c.playerName) +": <col=ff0000>" + Misc.optimizeText(playerCommand.substring(5)) +"</col>");
						}
						if (c.playerRights == 5) {
							c2.sendMessage("[S.Donator] @cr4@@or3@" +   Misc.capitalize(c.playerName) +": <col=0101DF>" + Misc.optimizeText(playerCommand.substring(5)) +"</col>");
						}
						if (c.playerRights == 6) {
							c2.sendMessage("[E.Donator] @cr5@@or3@" +   Misc.capitalize(c.playerName) +": <col=088A08>" + Misc.optimizeText(playerCommand.substring(5)) +"</col>");
						}
						if (c.playerRights == 7) {
							c2.sendMessage("[Respected] @cr6@@or3@" +   Misc.capitalize(c.playerName) +": <col=5F04B4>" + Misc.optimizeText(playerCommand.substring(5)) +"</col>");
						}
						if (c.playerRights == 8) {
							c2.sendMessage("[Veteran] @cr7@@or3@" +   Misc.capitalize(c.playerName) +": <col=8A4B08>" + Misc.optimizeText(playerCommand.substring(5)) +"</col>");
						}
						if (c.playerRights == 9) {
							c2.sendMessage("[Forums Admin] @cr8@@or3@" +   Misc.capitalize(c.playerName) +": <col=2880BC>" + Misc.optimizeText(playerCommand.substring(5)) +"</col>");
						}
					}
				}

		}));

	}
}
