package server.game.players.packets.commands;

import java.util.function.BiPredicate;

import org.Vote.MainLoader;

import server.Config;
import server.Connection;
import server.Server;
import server.game.content.ItemSpawnSearch;
import server.game.content.PlayerOwnedShop;
import server.game.npcs.WorldAdventurer;
import server.game.players.Client;
import server.game.players.PlayerHandler;
import server.game.players.packets.Commands;
import core.util.Misc;
import core.util.rspswebstore;

/**
 * Commands gated to playerRights 1-3, including the restored ban/kick.
 *
 * Generated by build/purge/gen-command-registry.js. Do not edit by hand.
 */
final class ModeratorCommands {

	private ModeratorCommands() {
	}

	static void register() {
		CommandHandler.register(Command.prefix("mute", 1, 3, (c, playerCommand) -> {
				try {
					String playerToBan = playerCommand.substring(5);
					Connection.addNameToMuteList(playerToBan);
					for (int i = 0; i < Config.MAX_PLAYERS; i++) {
						if (PlayerHandler.players[i] != null) {
							if (PlayerHandler.players[i].playerName.equalsIgnoreCase(playerToBan)) {
								@SuppressWarnings("unused")
								Client c2 = (Client) PlayerHandler.players[i];
								//c2.sendMessage("You have been muted by: " + Misc.capitalize(c.playerName) + ".");
								break;
							}
						}
					}
				} catch (Exception e) {
					c.sendMessage("Player is probably offline.");
				}
		}));

		CommandHandler.register(Command.prefix("xteleto", 1, 3, (c, playerCommand) -> {
				String name = playerCommand.substring(8);
				for (int i = 0; i < Config.MAX_PLAYERS; i++) {
					if (PlayerHandler.players[i] != null) {
						if (PlayerHandler.players[i].playerName.equalsIgnoreCase(name)) {
							c.getPA().movePlayer(PlayerHandler.players[i].getX(), PlayerHandler.players[i].getY(), PlayerHandler.players[i].position.heightLevel);
						}
					}
				}			
		}));

		CommandHandler.register(Command.prefix("ipmute", 1, 3, (c, playerCommand) -> {
					try {
						String playerToBan = playerCommand.substring(7);
						for (int i = 0; i < Config.MAX_PLAYERS; i++) {
							if (PlayerHandler.players[i] != null) {
								if (PlayerHandler.players[i].playerName.equalsIgnoreCase(playerToBan)) {
									Connection.addIpToMuteList(PlayerHandler.players[i].connectedFrom);
									c.sendMessage("You have IP Muted the user: " + PlayerHandler.players[i].playerName);
									@SuppressWarnings("unused")
									Client c2 = (Client) PlayerHandler.players[i];
									//c2.sendMessage("You have been muted by: " + Misc.capitalize(c.playerName));
									break;
								}
							}
						}
					} catch (Exception e) {
						c.sendMessage("Player is probably offline.");
					}
				if (playerCommand.startsWith("ban")) { // use as ::ban name
					try {	
						String playerToBan = playerCommand.substring(4);
						Connection.addNameToBanList(playerToBan);
						Connection.addNameToFile(playerToBan);
						for(int i = 0; i < Config.MAX_PLAYERS; i++) {
							if(PlayerHandler.players[i] != null) {
								if(PlayerHandler.players[i].playerName.equalsIgnoreCase(playerToBan)) {
									PlayerHandler.players[i].disconnected = true;
								} 
							}
						}
					} catch(Exception e) {
						c.sendMessage("Player is not online.");
					}
				}
				if (playerCommand.startsWith("kick")) {
					try {	
						String playerToKick = playerCommand.substring(5);
						for(int i = 0; i < Config.MAX_PLAYERS; i++) {
							if(PlayerHandler.players[i] != null) {
								if(PlayerHandler.players[i].playerName.equalsIgnoreCase(playerToKick)) {
									PlayerHandler.players[i].disconnected = true;
									PlayerHandler.players[i].properLogout = true;
								} 
							}
						}
					} catch(Exception e) {
						c.sendMessage("Player is not online.");
					}
				}
		}));


		// Restored in the Phase 3.5 follow-up: these two sat inside the `ipmute` block
		// and could never run. The trailing space is deliberate -- `startsWith("ban")`
		// also matches `banki`/`banke`, which are player commands registered earlier.
		CommandHandler.register(Command.prefix("ban ", 1, 3, (c, playerCommand) -> {
			try {
				String playerToBan = playerCommand.substring(4);
				Connection.addNameToBanList(playerToBan);
				Connection.addNameToFile(playerToBan);
				for (int i = 0; i < Config.MAX_PLAYERS; i++) {
					if (PlayerHandler.players[i] != null) {
						if (PlayerHandler.players[i].playerName.equalsIgnoreCase(playerToBan)) {
							PlayerHandler.players[i].disconnected = true;
						}
					}
				}
			} catch (Exception e) {
				c.sendMessage("Player is not online.");
			}
		}));

		CommandHandler.register(Command.prefix("kick ", 1, 3, (c, playerCommand) -> {
			try {
				String playerToKick = playerCommand.substring(5);
				for (int i = 0; i < Config.MAX_PLAYERS; i++) {
					if (PlayerHandler.players[i] != null) {
						if (PlayerHandler.players[i].playerName.equalsIgnoreCase(playerToKick)) {
							PlayerHandler.players[i].disconnected = true;
							PlayerHandler.players[i].properLogout = true;
						}
					}
				}
			} catch (Exception e) {
				c.sendMessage("Player is not online.");
			}
		}));
	}
}
