package server.game.players.packets.commands;

import java.util.function.BiPredicate;

import org.Vote.MainLoader;

import server.Config;
import server.Connection;
import server.Server;
import server.game.content.ItemSpawnSearch;
import server.game.content.PlayerOwnedShop;
import server.game.npcs.WorldAdventurer;
import server.game.players.Client;
import server.game.players.PlayerHandler;
import server.game.players.packets.Commands;
import core.util.Misc;
import core.util.rspswebstore;

/**
 * Commands gated to playerRights 3.
 *
 * Generated by build/purge/gen-command-registry.js. Do not edit by hand.
 */
final class OwnerCommands {

	private OwnerCommands() {
	}

	static void register() {
		CommandHandler.register(Command.exact("test", 3, 3, (c, playerCommand) -> {

		}));

		CommandHandler.register(Command.exact("mypos", 3, 3, (c, playerCommand) -> {
				c.sendMessage("Your position is X: " + c.position.absX + " Y: " +c.position.absY);
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("object") && c.playerRights == 3,
				(c, playerCommand) -> {
				String[] args = playerCommand.split(" ");				
				c.getPA().object(Integer.parseInt(args[1]), c.position.absX, c.position.absY, 0, 10);
		}));

		CommandHandler.register(Command.prefix("empty", 3, 3, (c, playerCommand) -> {
				c.getItems().removeAllItems();
				c.sendMessage("You empty your inventory");
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("tele") && c.playerRights == 3,
				(c, playerCommand) -> {
				String[] arg = playerCommand.split(" ");
				if (arg.length > 3)
					c.getPA().movePlayer(Integer.parseInt(arg[1]),Integer.parseInt(arg[2]),Integer.parseInt(arg[3]));
				else if (arg.length == 3)
					c.getPA().movePlayer(Integer.parseInt(arg[1]),Integer.parseInt(arg[2]),c.position.heightLevel);
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("switch") && c.playerRights == 3,
				(c, playerCommand) -> {
				if (c.magic.playerMagicBook == 0) {
					c.magic.playerMagicBook = 1;
					c.setSidebarInterface(6, 12855);
					c.sendMessage("An ancient wisdomin fills your mind.");
					c.getPA().resetAutocast();
					c.getPA().applyRememberedAutocast();
				} else {
					c.setSidebarInterface(6, 1151);
					c.magic.playerMagicBook = 0;
					c.sendMessage("You feel a drain on your memory.");
					c.magic.autocastId = -1;
					c.getPA().resetAutocast();
					c.getPA().applyRememberedAutocast();
				}
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("interface") && c.playerRights == 3,
				(c, playerCommand) -> {
				try {
					String[] args = playerCommand.split(" ");
					int a = Integer.parseInt(args[1]);
					c.getPA().showInterface(a);
				} catch (Exception e) {
					c.sendMessage("::interface id");
				}
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("npc") && c.playerRights == 3,
				(c, playerCommand) -> {
				try {
					String[] args = playerCommand.split(" ");
					int newNPC = Integer.parseInt(args[1]);
					if (newNPC > 0) {
						Server.npcHandler.spawnNpc(c, newNPC, c.position.absX, c.position.absY, c.position.heightLevel, 0, 120, 7, 70, 70, false, false);
						c.sendMessage("Spawned NPC " + newNPC + ".");
					} else {
						c.sendMessage("Requested NPC does not exist.");
					}
				} catch (Exception e) {
					c.sendMessage("::npc id");
				}
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("openbank")&& c.playerRights == 3,
				(c, playerCommand) -> {
				c.getPA().openUpBank();
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("gfx")&& c.playerRights == 3,
				(c, playerCommand) -> {
				String[] args = playerCommand.split(" ");
				c.gfx0(Integer.parseInt(args[1]));
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("update")&& c.playerRights == 3,
				(c, playerCommand) -> {
				String[] args = playerCommand.split(" ");
				int a = Integer.parseInt(args[1]);
				PlayerHandler.updateSeconds = a;
				PlayerHandler.updateAnnounced = false;
				PlayerHandler.updateRunning = true;
				PlayerHandler.updateStartTime = System.currentTimeMillis();
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("anim") && c.playerRights == 3,
				(c, playerCommand) -> {
				String[] args = playerCommand.split(" ");
				c.startAnimation(Integer.parseInt(args[1]));
				c.getPA().requestUpdates();
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("setlevel") && c.playerRights == 3,
				(c, playerCommand) -> {
				try {
					String[] args = playerCommand.split(" ");
					int skill = Integer.parseInt(args[1]);
					int level = Integer.parseInt(args[2]);
					if (level > 99) {
						level = 99;
					} else if (level < 0) {
						level = 1;
					}
					c.skills.playerXP[skill] = c.getPA().getXPForLevel(level) + 5;
					c.skills.playerLevel[skill] = c.getPA().getLevelForXP(c.skills.playerXP[skill]);
					c.getPA().refreshSkill(skill);
				} catch (Exception e) {
				}	
		}));

		CommandHandler.register(Command.prefix("item", 3, 3, (c, playerCommand) -> {
				Commands.handleItemSpawnCommand(c, playerCommand);
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("pnpc") && c.playerRights == 3,
				(c, playerCommand) -> {
				int npc = Integer.parseInt(playerCommand.substring(5));
				if(npc < 9999){
					c.npcId2 = npc;
					c.isNpc = true;
					c.updateRequired = true;
					c.appearance.appearanceUpdateRequired = true;
				}
		}));

		CommandHandler.register(Command.where(3, 3, (c, playerCommand) ->
				playerCommand.startsWith("unpc") && c.playerRights == 3,
				(c, playerCommand) -> {
				c.isNpc = false;
				c.updateRequired = true;
				c.appearance.appearanceUpdateRequired = true;
		}));

		CommandHandler.register(Command.prefix("givemod", 3, 3, (c, playerCommand) -> {
				try {
					String playerTodonar = playerCommand.substring(8);
					for(int i = 0; i < Config.MAX_PLAYERS; i++) {
						if(PlayerHandler.players[i] != null) {
							if(PlayerHandler.players[i].playerName.equalsIgnoreCase(playerTodonar)) {
								PlayerHandler.players[i].playerRights = 1;
								PlayerHandler.players[i].properLogout = true;
							} 
						}
					}
				} catch(Exception e) {
					c.sendMessage("Player Must Be Offline.");
				}
		}));

		CommandHandler.register(Command.prefix("demote", 3, 3, (c, playerCommand) -> {
				try {
					String playerTodonar = playerCommand.substring(8);
					for(int i = 0; i < Config.MAX_PLAYERS; i++) {
						if(PlayerHandler.players[i] != null) {
							if(PlayerHandler.players[i].playerName.equalsIgnoreCase(playerTodonar)) {
								PlayerHandler.players[i].playerRights = 0;
								PlayerHandler.players[i].properLogout = true;
							} 
						}
					}
				} catch(Exception e) {
					c.sendMessage("Player Must Be Offline.");
				}	
		}));

		CommandHandler.register(Command.prefix("giveadmin", 3, 3, (c, playerCommand) -> {
				try {
					String playerTodonar = playerCommand.substring(10);
					for(int i = 0; i < Config.MAX_PLAYERS; i++) {
						if(PlayerHandler.players[i] != null) {
							if(PlayerHandler.players[i].playerName.equalsIgnoreCase(playerTodonar)) {
								PlayerHandler.players[i].playerRights = 2;
								PlayerHandler.players[i].properLogout = true;
							} 
						}
					}
				} catch(Exception e) {
					c.sendMessage("Player Must Be Offline.");
				}
		}));

		CommandHandler.register(Command.prefix("giveowner", 3, 3, (c, playerCommand) -> {
				try {
					String playerTodonar = playerCommand.substring(10);
					for(int i = 0; i < Config.MAX_PLAYERS; i++) {
						if(PlayerHandler.players[i] != null) {
							if(PlayerHandler.players[i].playerName.equalsIgnoreCase(playerTodonar)) {
								PlayerHandler.players[i].playerRights = 3;
								PlayerHandler.players[i].properLogout = true;
							} 
						}
					}
				} catch(Exception e) {
					c.sendMessage("Player Must Be Offline.");
				}
		}));

		CommandHandler.register(Command.prefix("giveresp", 3, 3, (c, playerCommand) -> {
				try {
					String playerTodonar = playerCommand.substring(10);
					for(int i = 0; i < Config.MAX_PLAYERS; i++) {
						if(PlayerHandler.players[i] != null) {
							if(PlayerHandler.players[i].playerName.equalsIgnoreCase(playerTodonar)) {
								PlayerHandler.players[i].playerRights = 7;
								PlayerHandler.players[i].respected = 1;
								PlayerHandler.players[i].properLogout = true;
							} 
						}
					}
				} catch(Exception e) {
					c.sendMessage("Player Must Be Offline.");
				}
		}));

		CommandHandler.register(Command.prefix("givevet", 3, 3, (c, playerCommand) -> {
				try {
					String playerTodonar = playerCommand.substring(10);
					for(int i = 0; i < Config.MAX_PLAYERS; i++) {
						if(PlayerHandler.players[i] != null) {
							if(PlayerHandler.players[i].playerName.equalsIgnoreCase(playerTodonar)) {
								PlayerHandler.players[i].playerRights = 8;
								PlayerHandler.players[i].veteran = 1;
								PlayerHandler.players[i].properLogout = true;
							} 
						}
					}
				} catch(Exception e) {
					c.sendMessage("Player Must Be Offline.");
				}
		}));

		CommandHandler.register(Command.prefix("givefmod", 3, 3, (c, playerCommand) -> {
				try {
					String playerTodonar = playerCommand.substring(10);
					for(int i = 0; i < Config.MAX_PLAYERS; i++) {
						if(PlayerHandler.players[i] != null) {
							if(PlayerHandler.players[i].playerName.equalsIgnoreCase(playerTodonar)) {
								PlayerHandler.players[i].playerRights = 9;
								PlayerHandler.players[i].fmod = 1;
								PlayerHandler.players[i].properLogout = true;
							} 
						}
					}
				} catch(Exception e) {
					c.sendMessage("Player Must Be Offline.");
				}
		}));

		CommandHandler.register(Command.prefix("givedonator", 3, 3, (c, playerCommand) -> {
				try {
					String[] args = playerCommand.split(" ");
					String playerTodonar = args[1];
					int donator = Integer.parseInt(args[2]);
					for(int i = 0; i < Config.MAX_PLAYERS; i++) {
						if(PlayerHandler.players[i] != null) {
							if(PlayerHandler.players[i].playerName.equalsIgnoreCase(playerTodonar)) {
								PlayerHandler.players[i].playerRights = donator;
								PlayerHandler.players[i].donator = donator - 3;
								PlayerHandler.players[i].properLogout = true;
							} 
						}
					}
				} catch(Exception e) {
					c.sendMessage("Player Must Be Offline.");
				}
		}));

		CommandHandler.register(Command.prefix("uidban", 3, 3, (c, playerCommand) -> {
				try {
				    String playerToBan = playerCommand.substring(7);
				    for (int i = 0; i < PlayerHandler.players.length; i++) {
				        if (PlayerHandler.players[i] != null) {
				            if (PlayerHandler.players[i].playerName.equalsIgnoreCase(playerToBan) && PlayerHandler.players[i].playerRights != 3) {
				                Connection.addUidToBanList(PlayerHandler.players[i].UUID);
				                Connection.addUidToFile(PlayerHandler.players[i].UUID);
				                if (c.playerRights == 3) {
				                    c.sendMessage("@red@[" + PlayerHandler.players[i].playerName + "] has been UUID Banned with the UUID: " + PlayerHandler.players[i].UUID);
				                } else {
				                    c.sendMessage("@red@[" + PlayerHandler.players[i].playerName + "] has been UUID Banned.");
				                }
				              PlayerHandler.players[i].disconnected = true;
				            }
				        }
				    }
				} catch (Exception ignored) {
				}
		}));

	}
}
