package server.game.players.packets.commands;

import java.util.function.BiPredicate;

import org.Vote.MainLoader;

import server.Config;
import server.Connection;
import server.Server;
import server.game.content.ItemSpawnSearch;
import server.game.content.PlayerOwnedShop;
import server.game.npcs.WorldAdventurer;
import server.game.players.Client;
import server.game.players.PlayerHandler;
import server.game.players.packets.Commands;
import core.util.Misc;
import core.util.rspswebstore;

/**
 * Commands gated to playerRights 2-3, plus the three that were nested one level shallower and so actually run for rights 1-3 (unban, xteletome, ipban).
 *
 * Generated by build/purge/gen-command-registry.js. Do not edit by hand.
 */
final class StaffCommands {

	private StaffCommands() {
	}

	static void register() {
		CommandHandler.register(Command.where(2, 3, (c, playerCommand) ->
				playerCommand.equalsIgnoreCase("clip") || playerCommand.startsWith("clip "),
				(c, playerCommand) -> {
				Commands.handleClipDebug(c, playerCommand);
		}));

		CommandHandler.register(Command.where(2, 3, (c, playerCommand) ->
				playerCommand.equalsIgnoreCase("master") && c.playerRights == 3,
				(c, playerCommand) -> {
				for (int i = 0; i < 23; i++) {
					c.getPA().addSkillXP(c.getPA().getXPForLevel(100), i);
					c.getPA().refreshSkill(i);	
					c.getPA().requestUpdates();
				}
		}));

		CommandHandler.register(Command.where(2, 3, (c, playerCommand) ->
				playerCommand.startsWith("item") && c.playerRights == 3,
				(c, playerCommand) -> {
				Commands.handleItemSpawnCommand(c, playerCommand);
		}));

		CommandHandler.register(Command.prefix("unipban", 2, 3, (c, playerCommand) -> {
				try {
					String playerToBan = playerCommand.substring(9);
					for (int i = 0; i < Config.MAX_PLAYERS; i++) {
						if (PlayerHandler.players[i] != null) {
							if (PlayerHandler.players[i].playerName.equalsIgnoreCase(playerToBan)) {
								Connection.unIPBanUser(PlayerHandler.players[i].connectedFrom);
								c.sendMessage("You have un-IPbanned the user: " + PlayerHandler.players[i].playerName);
								break;
							}
						}
					}
				} catch (Exception e) {
					c.sendMessage("Player is probably offline.");
				}
		}));

		CommandHandler.register(Command.prefix("unipmute", 2, 3, (c, playerCommand) -> {
				try {
					String playerToBan = playerCommand.substring(9);
					for (int i = 0; i < Config.MAX_PLAYERS; i++) {
						if (PlayerHandler.players[i] != null) {
							if (PlayerHandler.players[i].playerName.equalsIgnoreCase(playerToBan)) {
								Connection.unIPMuteUser(PlayerHandler.players[i].connectedFrom);
								c.sendMessage("You have un IP-muted the user: " + PlayerHandler.players[i].playerName);
								break;
							}
						}
					}
				} catch (Exception e) {
					c.sendMessage("Player is probably offline.");
				}
		}));

		CommandHandler.register(Command.prefix("unmute", 2, 3, (c, playerCommand) -> {
				try {
					String playerToBan = playerCommand.substring(7);
					Connection.unMuteUser(playerToBan);
				} catch (Exception e) {
					c.sendMessage("Player is probably offline.");
				}
		}));

		CommandHandler.register(Command.prefix("unban", 1, 3, (c, playerCommand) -> {
				try {
					String playerToBan = playerCommand.substring(6);
					Connection.removeNameFromBanList(playerToBan);
					c.sendMessage(playerToBan + " has been unbanned.");
				} catch (Exception e) {
					c.sendMessage("Player is probably offline.");
				}
		}));

		CommandHandler.register(Command.prefix("xteletome", 1, 3, (c, playerCommand) -> {
				try {
					String playerToBan = playerCommand.substring(10);
					for (int i = 0; i < Config.MAX_PLAYERS; i++) {
						if (PlayerHandler.players[i] != null) {
							if (PlayerHandler.players[i].playerName
									.equalsIgnoreCase(playerToBan)) {
								Client c2 = (Client) PlayerHandler.players[i];
								c2.position.teleportToX = c.position.absX;
								c2.position.teleportToY = c.position.absY;
								c2.position.heightLevel = c.position.heightLevel;
								c.sendMessage("You have teleported "
										+ c2.playerName + " to you.");
								c2.sendMessage("You have been teleported to "
										+ c.playerName + ".");
							}
						}
					}
				} catch (Exception e) {
					c.sendMessage("Player Must Be Offline.");
				}
		}));

		CommandHandler.register(Command.prefix("ipban", 1, 3, (c, playerCommand) -> {
				try {
					String playerToBan = playerCommand.substring(6);
					for (int i = 0; i < Config.MAX_PLAYERS; i++) {
						if (PlayerHandler.players[i] != null) {
							if (PlayerHandler.players[i].playerName.equalsIgnoreCase(playerToBan)) {
								Connection.addIpToBanList(PlayerHandler.players[i].connectedFrom);
								Connection.addIpToFile(PlayerHandler.players[i].connectedFrom);
								c.sendMessage("You have IP banned the user: " + PlayerHandler.players[i].playerName + " with the host: " + PlayerHandler.players[i].connectedFrom);
								PlayerHandler.players[i].disconnected = true;
							}
						}
					}
				} catch (Exception e) {
					c.sendMessage("Player is probably offline.");
				}
		}));

	}
}
