package server.game.players.actions.dialogues;

import server.Config;
import server.game.players.DialogueHandler;

/**
 * Data tables for the mechanical NPC and player chat dialogues lifted out of
 * {@link DialogueHandler#sendDialogues(int, int)}.
 *
 * Row layout: { dialogueId, lines..., npc, name, nextChat } for NPC chat and
 * { dialogueId, lines..., nextChat } for player chat. An npc of {@link #TALKING_NPC}
 * means "the npc being talked to" (c.talkingNpc); any other value is the literal
 * npc id the original switch used.
 *
 * Generated by build/purge/gen-dialogue-families.js. Do not edit by hand.
 */
public final class ChatDialogues {

	private static final int TALKING_NPC = -1;

	private static final Object[][] NPC_CHAT1_NEXT_CHAT = {
			{ 505, "Welcome to Bounty Hunter.", -1, "Bounty Hunter Guard", 506 },
			{ 512, "You weak warrior. Your combatlevel is far from this!", -1, "Veteran Hervi", 0 },
			{ 513, "Your reward has been added to your bank. Your future is bright, warrior.", -1, "Veteran Hervi", 0 },
			{ 600, "What am I to do?", -1, "Cook", 601 },
			{ 608, "Oh please! Hurry then!", -1, "Cook", 0 },
			{ 612, "I don't have time for your jibber-jabber!", -1, "Cook", 0 },
			{ 613, "Does it look like I have the time?", -1, "Cook", 0 },
			{ 615, "How are you getting on with finding the ingredients?", -1, "Cook", 616 },
			{ 622, "Maybe, but I won't be holding my breath.", -1, "Cook", 623 },
			{ 624, "Thanks for helping me out friend!", -1, "Cook", 0 },
			{ 1099, "Greetings, thanks for your help advernturer.", -1, "Duke Horacio", 0 },
			{ 1100, "Greetings. Welcome to my castle.", -1, "Duke Horacio", 1103 },
			{ 1150, "That's me, but why would you be doing that?", -1, "Head Wizard", 1151 },
			{ 1155, "Wow! This is incredible!", -1, "Head Wizard", 1156 },
			{ 1173, "Do you want to buy some runes?", -1, "Aubury", 1174 },
			{ 1176, "Really? surely he can't have...? Please, let me have it.", -1, "Aubury", 1180 },
			{ 1181, "My gratitude, adventurer, for bringing me this research", -1, "Aubury", 1182 },
			{ 1192, "Greetings, have you deliverd the Research Package yet my friend?", -1, "Head Wizard", 1193 },
			{ 1194, "May I have them?", -1, "Head Wizard", 1195 },
			{ 3, "'Ello, and what are you after then?", -1, "Chaeldar", 4 },
			{ 11, "'Ello, and what are you after then?", -1, "Chaeldar", 12 },
			{ 13, "'Ello, and what are you after then?", -1, "Chaeldar", 14 },
			{ 58, "Where would you like me to take you?", -1, "Sailor", 59 },
			{ 60, "Welcome to the church of Entrana, my brother.", -1, "Brother Jered", 61 },
			{ 474, "I hope your journey is coming along well!", 2244, "Lumbridge Guide", 0 },
			{ 516, "Let's change your appearance now.", 599, "Make-over mage", 517 },
			{ 519, "Sorry I forgot something!", 2244, "Lumbridge Guide", 520 },
			{ 63, "Would you like to change your appearance?", -1, "Make-over mage", 64 },
			{ 66, "Do you want to take a look at my fishing supplies?", -1, "Master fisher", 67 },
			{ 77, "Hello, do you want to take a look at my farming shop?", -1, "Farmer Brumty", 78 },
			{ 81, "Do you want me to teleport you to the slayer tower?", -1, "Old Man", 82 },
			{ 88, "Do you want to go to the gnome agility course?", -1, "Gnome", 89 },
			{ 1000, "Hello, how may I help you?", -1, "Banker", 1001 },
			{ 1002, "Sure thing.", -1, "Banker", 1003 },
			{ 1006, "So how are you today?", -1, "Zaff", 1007 },
			{ 1008, "Hi...", -1, "Thessalia", 1009 },
			{ 1010, "I guess not so good...", -1, "Thessalia", 1011 },
			{ 996, "I don't want to talk to people unexperienced with magic!", -1, "Aubury", 0 },
			{ 997, "Take a look in the chest over there.", -1, "Tramp", 0 },
			{ 999, "Hello!", -1, "Shop Keeper", 0 },
			{ 998, "You have no business here!", -1, "Guard", 0 },
			{ 2000, "I hope you are having a great day in "+Config.SERVER_NAME+"!", -1, "", 2001 },
	};

	private static final Object[][] NPC_CHAT2_NEXT_CHAT = {
			{ 750, "Hello. I am able to switch your rank.", "Which rank do you want to display?", -1, "Rank Switcher", 751 },
			{ 555, "Hello. I can travel you around the world.", "Which spot do you want me to travel you to?", -1, "Traveler", 556 },
			{ 557, "Hello. I can travel you around the world.", "Which spot do you want me to travel you to?", -1, "Traveler", 558 },
			{ 559, "Hello. I can sail you around the world.", "Which spot do you want me to sail you to?", -1, "Sailor", 560 },
			{ 561, "Hello. I can sail you around the world.", "Which spot do you want me to sail you to?", -1, "Sailor", 562 },
			{ 563, "Hello. I can sail you around the world.", "Which spot do you want me to sail you to?", -1, "Sailor", 564 },
			{ 565, "Hello. I can sail you to Ape Atoll.", "Want me to take you to Ape Atoll?", -1, "Sailor", 566 },
			{ 567, "Hello. I can teleport you around the world.", "Which spot do you want me to teleport you to?", -1, "Traveler", 568 },
			{ 569, "Hello. I can teleport you around the world.", "Which spot do you want me to teleport you to?", -1, "Traveler", 570 },
			{ 571, "Hello. I can teleport you around the gnome city.", "Which spot do you want me to teleport you to?", -1, "Gnome", 572 },
			{ 573, "Hello. I can teleport you around the elves city.", "Which spot do you want me to teleport you to?", -1, "Elf", 574 },
			{ 575, "Hello. I can take you to the Warriors' Guild.", "Want me to take you there?", -1, "Traveler", 576 },
			{ 577, "Hello. I can travel you around Varrock.", "Where do you want me to travel you to?", -1, "Traveler", 578 },
			{ 579, "Hello. I can travel you around Falador.", "Where do you want me to travel you to?", -1, "Traveler", 580 },
			{ 581, "Hello. I can travel you around Lumbridge.", "Where do you want me to travel you to?", -1, "Traveler", 582 },
			{ 583, "Hello. I can travel you around Draynor.", "Where do you want me to travel you to?", -1, "Traveler", 584 },
			{ 585, "Hello. I can travel you around Al-Kharid.", "Where do you want me to travel you to?", -1, "Traveler", 586 },
			{ 587, "Hello. I can travel you around the Kharidian Desert.", "Where do you want me to travel you to?", -1, "Traveler", 588 },
			{ 589, "Hello. I can travel you around Morytania.", "Where do you want me to travel you to?", -1, "Traveler", 590 },
			{ 591, "Hello. I can travel you around Karamja.", "Where do you want me to travel you to?", -1, "Traveler", 592 },
			{ 593, "Hello. I can travel you to Brimhaven Dungeon.", "Do you want me to take you there?", -1, "Traveler", 594 },
			{ 595, "Hello. I can travel you to Taverley Dungeon.", "Do you want me to take you there?", -1, "Traveler", 596 },
			{ 620, "I'm agraid not, only the big cheeses get to dine with the", "Duke.", -1, "Cook", 621 },
			{ 1104, "Well, it's not really a quest, but i recently discovered", "this strange talisman.", -1, "Duke Horacio", 1105 },
			{ 1105, "It's not like anything I have seen before. Would you", "take it to the head wizard in the basement of", -1, "Duke Horacio", 1106 },
			{ 1106, "the Wizards' Tower for me? It should not take you", "very long at all and I would be awfully grateful.", -1, "Duke Horacio", 1107 },
			{ 1152, "Did he now? Well, that IS interesting. Hand it over,", "then, adventurer ", -1, "Head Wizard", 1153 },
			{ 460, "Welcome to "+Config.SERVER_NAME+"!", "I will be your guide today, you can call me, Guide.", 2244, "Lumbridge Guide", 461 },
			{ 463, "I also want to mention,", "That this server is an intense economy server.", 2244, "Lumbridge Guide", 464 },
			{ 464, "Not one item that is obtainable by bosses or minigames", "is obtainable in the shops.", 2244, "Lumbridge Guide", 465 },
			{ 465, "The server relies on supply and demand. For example,", "food is highly priced but has a low stock,", 2244, "Lumbridge Guide", 466 },
			{ 466, "Which encourages skilling, trading", "and interacting with players!", 2244, "Lumbridge Guide", 467 },
			{ 468, "Another important feature here in "+Config.SERVER_NAME+", is combat!", "Combat is almost like Runescape has!", 2244, "Lumbridge Guide", 470 },
			{ 470, "You can train, and travel around "+Config.SERVER_NAME+",", "By using the teleport book in your magic tab.", 2244, "Lumbridge Guide", 599 },
			{ 597, "Here you can travel to cities and monsters.", "Just talk to one of the NPCs which are standing here!", 2244, "Lumbridge Guide", 700 },
			{ 598, "Here you can sail to cities and monsters.", "Just talk to one of the NPCs which are standing here!", 2244, "Lumbridge Guide", 701 },
			{ 520, "Since you're a special player of "+Config.SERVER_NAME+", you may", "choose your Experience rate.", 2244, "Lumbridge Guide", 521 },
			{ 69, "You even defeated TzTok-Jad, I am most impressed!", "Please accept this gift as a reward.", -1, "Tzhaar-Mej-Tal", -1 },
			{ 70, "Hey, do you want me to bring you into the icy cavern?", "I can't help you in there though, it's too dangerous.", -1, "Wizard Mizgog", 71 },
			{ 75, "Hello sir, I am specialized in tribal weaponry. Do you", "want to take a look at my shop?", -1, "Tribal Weapon Salesman", 76 },
			{ 84, "Hey there! I've gained a lot of gear lately. Do you", "want to take a look?", -1, "Bandit shopkeeper", 85 },
			{ 86, "I've got dwarf multicannon parts and ammo.", "Want to take a look?", -1, "Nulodion", 87 },
			{ 1012, "None of your business! Do you want to buy any", "clothes or not?!", -1, "Thessalia", 1013 },
	};

	private static final Object[][] NPC_CHAT3_NEXT_CHAT = {
			{ 603, "Oh dear, oh dear, oh dear, I'm in a terrible terrible", "mess! It's the Duke's birthday today, and I should be", "making him a lovely big birthday cake!", -1, "Cook", 604 },
			{ 611, "You can find wheat to make flour at the mill.", "You can find eggs by killing chickens.", "You can find milk by using a bucket on a cow", -1, "Cook", 0 },
			{ 1156, "Th-this talisman you brougth me... it is the last piece of", "the puzzle. Finally! The legacy of our ancestors will", "return to us once more!", -1, "Head Wizard", 1157 },
			{ 1157, "I need time to study this, adventurer", "please go to the mighty city of varrock, located north-east of here,", "there is a certain shop that sells magical runes.", -1, "Head Wizard", 1158 },
			{ 462, "To start off, this server is jam-packed with content,", "Including tons of skills and thrilling minigames and bosses,", "Where you can fight for valuable rares.", 2244, "Lumbridge Guide", 463 },
	};

	private static final Object[][] NPC_CHAT4_NEXT_CHAT = {
			{ 506, "At this place you can kill other players in order to", "recieve BH Kills. With these kills you can be rewarded", "with money. You need atleast 10 Bounty Kills in order to", "claim this cash. What combat level are you?", -1, "Veteran Hervi", 507 },
			{ 604, "I've forgotten to buy the ingredients. I'll never get", "them in time now. He'll sack me! What will I do? I have", "four children and a goat to look after. Would you help", "me? Please?", -1, "Cook", 605 },
			{ 5, "Hello adventurer...", "My name is Kolodion, the master of this mage bank.", "Would you like to play a minigame in order ", "to earn points towards receiving magic related prizes?", -1, "Kolodion", 6 },
			{ 6, "The way the game works is as follows...", "You will be teleported to the wilderness,", "You must kill mages to recieve points,", "redeem points with the chamber guardian.", -1, "Kolodion", 15 },
			{ 28, "Hello, I am the vote master.", " I handle the swapping of vote points for cash. I can also open", "the vote shop and page. So, what can I do for you?", "", -1, "Vote Master", 29 },
	};

	private static final Object[][] PLAYER_CHAT1_NEXT_CHAT = {
			{ 602, "What's wrong?", 603 },
			{ 606, "Yes, I'll help you.", 609 },
			{ 607, "I can't right now, Maybe later.", 608 },
			{ 610, "So where do I find these ingredients then?", 611 },
			{ 614, "You don't look so happy.", 603 },
			{ 619, "So do I get to go to the Duke's Party?", 620 },
			{ 1103, "Have you any quests for me?", 1104 },
			{ 1109, "Okay", 1110 },
			{ 1149, "I'm looking for the head wizard.", 1150 },
			{ 1193, "Yes, I have. He gave me some research notes for you.", 1194 },
			{ 61, "Thanks, brother Jered.", 0 },
			{ 461, "Well that's a great name to call you..", 462 },
			{ 467, "Hmm.. Seems rather interesting..", 468 },
			{ 65, "No thanks.", 0 },
			{ 1001, "I would like to access my bank account.", 1002 },
			{ 1005, "Hello Zaff.", 1006 },
			{ 1007, "I'm fine!", 0 },
			{ 1009, "Hello Thessalia, how are you?", 1010 },
			{ 1011, "What's wrong?", 1012 },
			{ 1013, "Err... Maybe later...", 0 },
			{ 2001, "Indeed, it is!", 0 },
	};

	private static final Object[][] PLAYER_CHAT2_NEXT_CHAT = {
			{ 621, "Well, maybe one day I'll be important enough to sit on", "the Duke's table", 622 },
	};

	private static final Object[][] PLAYER_CHAT3_NEXT_CHAT = {
			{ 1151, "The Duke of Lumbridge sent me to find him... er, you,", "I have a weird talisman that the Duke found. He said", "you would be interested in it.", 1152 },
	};

	private ChatDialogues() {
	}

	static void register() {
		for (Object[] row : NPC_CHAT1_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final int npc = (Integer) row[2];
			final String name = (String) row[3];
			final int nextChatValue = (Integer) row[4];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendNpcChat1(line1, npc == TALKING_NPC ? c.talkingNpc : npc, name);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : NPC_CHAT2_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final int npc = (Integer) row[3];
			final String name = (String) row[4];
			final int nextChatValue = (Integer) row[5];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendNpcChat2(line1, line2, npc == TALKING_NPC ? c.talkingNpc : npc, name);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : NPC_CHAT3_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final String line3 = (String) row[3];
			final int npc = (Integer) row[4];
			final String name = (String) row[5];
			final int nextChatValue = (Integer) row[6];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendNpcChat3(line1, line2, line3, npc == TALKING_NPC ? c.talkingNpc : npc, name);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : NPC_CHAT4_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final String line3 = (String) row[3];
			final String line4 = (String) row[4];
			final int npc = (Integer) row[5];
			final String name = (String) row[6];
			final int nextChatValue = (Integer) row[7];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendNpcChat4(line1, line2, line3, line4, npc == TALKING_NPC ? c.talkingNpc : npc, name);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : PLAYER_CHAT1_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final int nextChatValue = (Integer) row[2];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendPlayerChat1(line1);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : PLAYER_CHAT2_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final int nextChatValue = (Integer) row[3];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendPlayerChat2(line1, line2);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : PLAYER_CHAT3_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final String line3 = (String) row[3];
			final int nextChatValue = (Integer) row[4];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendPlayerChat3(line1, line2, line3);
				c.nextChat = nextChatValue;
			});
		}
	}

	static Object[][] NpcChat1NextChat() {
		final Object[][] copy = new Object[NPC_CHAT1_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = NPC_CHAT1_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] NpcChat2NextChat() {
		final Object[][] copy = new Object[NPC_CHAT2_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = NPC_CHAT2_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] NpcChat3NextChat() {
		final Object[][] copy = new Object[NPC_CHAT3_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = NPC_CHAT3_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] NpcChat4NextChat() {
		final Object[][] copy = new Object[NPC_CHAT4_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = NPC_CHAT4_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] PlayerChat1NextChat() {
		final Object[][] copy = new Object[PLAYER_CHAT1_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = PLAYER_CHAT1_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] PlayerChat2NextChat() {
		final Object[][] copy = new Object[PLAYER_CHAT2_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = PLAYER_CHAT2_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] PlayerChat3NextChat() {
		final Object[][] copy = new Object[PLAYER_CHAT3_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = PLAYER_CHAT3_NEXT_CHAT[i].clone();
		return copy;
	}
}
