package server.game.players.actions.dialogues;

import server.game.players.DialogueHandler;

/**
 * Data tables for the mechanical emote dialogues lifted out of
 * {@link DialogueHandler#sendDialogues(int, int)}.
 *
 * Each row is { dialogueId, arguments... }; a chat npc argument of -1 means
 * "the npc being talked to" (c.talkingNpc) and any other value is the literal npc
 * id the original switch used. Emote arguments are fixed per table and shown in
 * the table name.
 *
 * Generated by build/purge/gen-dialogue-families.js. Do not edit by hand.
 */
public final class EmoteChatDialogues {

	private static final int TALKING_NPC = -1;

	private static final Object[][] NPC_EMOTE1_CALM_CONTINUED_NEXT_CHAT = {
			{ 484, "What would you like to do/ask?", "Judge", 485 },
	};

	private static final Object[][] NPC_EMOTE1_EVIL_NEXT_CHAT = {
			{ 400, "Hello, and what are you after then?", "Vannaka", 401 },
	};

	private static final Object[][] NPC_EMOTE2_CALM_NEXT_CHAT = {
			{ 551, "Hello, I'm the master of Hunter.", "What can I do for you?", "Skill Master", 552 },
			{ 549, "Hello, I'm the master of Construction.", "What can I do for you?", "Skill Master", 550 },
			{ 415, "Hello, I'm the master of Agility.", "What can I do for you?", "Skill Master", 416 },
			{ 417, "Hello, I'm the master of Herblore.", "What can I do for you?", "Skill Master", 418 },
			{ 419, "Hello, I'm the master of Thieving.", "What can I do for you?", "Skill Master", 420 },
			{ 421, "Hello, I'm the master of Runecrafting.", "What can I do for you?", "Skill Master", 422 },
			{ 423, "Hello, I'm the master of Crafting.", "What can I do for you?", "Skill Master", 424 },
			{ 425, "Hello, I'm the master of Fletching.", "What can I do for you?", "Skill Master", 426 },
			{ 427, "Hello, I'm the master of Mining.", "What can I do for you?", "Skill Master", 428 },
			{ 429, "Hello, I'm the master of Smithing.", "What can I do for you?", "Skill Master", 430 },
			{ 431, "Hello, I'm the master of Fishing.", "What can I do for you?", "Skill Master", 432 },
			{ 433, "Hello, I'm the master of Cooking.", "What can I do for you?", "Skill Master", 434 },
			{ 435, "Hello, I'm the master of Firemaking.", "What can I do for you?", "Skill Master", 436 },
			{ 437, "Hello, I'm the master of Woodcutting.", "What can I do for you?", "Skill Master", 438 },
			{ 439, "Hello, I'm the master of Farming.", "What can I do for you?", "Skill Master", 440 },
			{ 442, "Hello, I'm the master of Slayer.", "What can I do for you?", "Skill Master", 443 },
			{ 444, "Hello, I'm the master of Strength.", "What can I do for you?", "Skill Master", 441 },
			{ 445, "Hello, I'm the master of Attack.", "What can I do for you?", "Skill Master", 446 },
			{ 447, "Hello, I'm the master of Hitpoints.", "What can I do for you?", "Skill Master", 448 },
			{ 449, "Hello, I'm the master of Defence.", "What can I do for you?", "Skill Master", 450 },
			{ 451, "Hello, I'm the master of Prayer.", "What can I do for you?", "Skill Master", 452 },
			{ 453, "Hello, I'm the master of Ranging.", "What can I do for you?", "Skill Master", 454 },
			{ 455, "Hello, I'm the master of Magic.", "What can I do for you?", "Skill Master", 456 },
	};

	private static final Object[][] NPC_EMOTE2_EVIL_NEXT_CHAT = {
			{ 409, "Sorry, but your current task is already easy.", "Please come back when you've finished it.", "Vannaka", 0 },
	};

	private static final Object[][] NPC_EMOTE3_CALM_CONTINUED_NEXT_CHAT = {
			{ 486, "Hello!", "I can bring you to several training zones in the desert.", "Where can I take you to?", "Cart Traveler", 479 },
			{ 487, "Hello!", "I can bring you to several training zones in the snow mountain.", "Where can I take you to?", "Traveler Joe", 480 },
			{ 488, "Hello!", "I can bring you to several training zones in the dungeons.", "Where can I take you to?", "Cart Traveler", 481 },
			{ 490, "Hello!", "I can sail you to several training zones.", "Where can I take you to?", "Sailor", 482 },
	};

	private static final Object[][] NPC_EMOTE4_CALM_CONTINUED_NEXT_CHAT = {
			{ 502, "Hello!", "I have privileges to reset your stats.", "However, I can reset only one stat at a time.", "Which stat do you want to reset?", "Stat Resetter", 503 },
			{ 483, "Hello!", "I'm the competition judge of the Ranging Guild.", "You can buy shots from me and shoot the targets", "for points. You can exchange the points at me.", "Judge", 484 },
	};

	private static final Object[][] PLAYER_EMOTE_CALM_CONTINUED_NEXT_CHAT = {
			{ 404, "I need another assignment!", 405 },
	};

	private static final Object[][] PLAYER_EMOTE_CALM_NEXT_CHAT = {
			{ 402, "I want to see the stuff you have for sale.", 403 },
	};

	private static final Object[][] PLAYER_EMOTE_HAPPY_NEXT_CHAT = {
			{ 411, "Alright, thank you!", 0 },
	};

	private EmoteChatDialogues() {
	}

	static void register() {
		for (Object[] row : NPC_EMOTE1_CALM_CONTINUED_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String name = (String) row[2];
			final int nextChatValue = (Integer) row[3];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendNpcChat(line1, dh.CALM_CONTINUED, name);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : NPC_EMOTE1_EVIL_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String name = (String) row[2];
			final int nextChatValue = (Integer) row[3];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendNpcChat(line1, dh.EVIL, name);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : NPC_EMOTE2_CALM_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final String name = (String) row[3];
			final int nextChatValue = (Integer) row[4];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendNpcChat(line1, line2, dh.CALM, name);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : NPC_EMOTE2_EVIL_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final String name = (String) row[3];
			final int nextChatValue = (Integer) row[4];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendNpcChat(line1, line2, dh.EVIL, name);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : NPC_EMOTE3_CALM_CONTINUED_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final String line3 = (String) row[3];
			final String name = (String) row[4];
			final int nextChatValue = (Integer) row[5];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendNpcChat(line1, line2, line3, dh.CALM_CONTINUED, name);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : NPC_EMOTE4_CALM_CONTINUED_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final String line3 = (String) row[3];
			final String line4 = (String) row[4];
			final String name = (String) row[5];
			final int nextChatValue = (Integer) row[6];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendNpcChat(line1, line2, line3, line4, dh.CALM_CONTINUED, name);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : PLAYER_EMOTE_CALM_CONTINUED_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final int nextChatValue = (Integer) row[2];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendPlayerChat(line1, dh.CALM_CONTINUED);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : PLAYER_EMOTE_CALM_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final int nextChatValue = (Integer) row[2];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendPlayerChat(line1, dh.CALM);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : PLAYER_EMOTE_HAPPY_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final int nextChatValue = (Integer) row[2];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendPlayerChat(line1, dh.HAPPY);
				c.nextChat = nextChatValue;
			});
		}
	}

	static Object[][] NpcEmote1CalmContinuedNextChat() {
		final Object[][] copy = new Object[NPC_EMOTE1_CALM_CONTINUED_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = NPC_EMOTE1_CALM_CONTINUED_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] NpcEmote1EvilNextChat() {
		final Object[][] copy = new Object[NPC_EMOTE1_EVIL_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = NPC_EMOTE1_EVIL_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] NpcEmote2CalmNextChat() {
		final Object[][] copy = new Object[NPC_EMOTE2_CALM_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = NPC_EMOTE2_CALM_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] NpcEmote2EvilNextChat() {
		final Object[][] copy = new Object[NPC_EMOTE2_EVIL_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = NPC_EMOTE2_EVIL_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] NpcEmote3CalmContinuedNextChat() {
		final Object[][] copy = new Object[NPC_EMOTE3_CALM_CONTINUED_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = NPC_EMOTE3_CALM_CONTINUED_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] NpcEmote4CalmContinuedNextChat() {
		final Object[][] copy = new Object[NPC_EMOTE4_CALM_CONTINUED_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = NPC_EMOTE4_CALM_CONTINUED_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] PlayerEmoteCalmContinuedNextChat() {
		final Object[][] copy = new Object[PLAYER_EMOTE_CALM_CONTINUED_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = PLAYER_EMOTE_CALM_CONTINUED_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] PlayerEmoteCalmNextChat() {
		final Object[][] copy = new Object[PLAYER_EMOTE_CALM_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = PLAYER_EMOTE_CALM_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] PlayerEmoteHappyNextChat() {
		final Object[][] copy = new Object[PLAYER_EMOTE_HAPPY_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = PLAYER_EMOTE_HAPPY_NEXT_CHAT[i].clone();
		return copy;
	}
}
