package server.game.players.actions.dialogues;

import server.game.players.DialogueHandler;

/**
 * Data tables for the mechanical option dialogues lifted out of
 * {@link DialogueHandler#sendDialogues(int, int)}.
 *
 * Row layout: { dialogueId, options..., assignments... }. The assignment columns
 * are the trailing c.dialogueAction / c.dialogueId / c.nextChat / c.teleAction
 * writes, in the order the original case performed them.
 *
 * Generated by build/purge/gen-dialogue-families.js. Do not edit by hand.
 */
public final class OptionDialogues {

	private static final Object[][] OPTION2_DIALOGUE_ACTION = {
			{ 564, "Port Khazard", "Port Phasmatys", 564 },
			{ 566, "Yes", "No", 566 },
			{ 576, "Yes", "No", 576 },
			{ 594, "Yes", "No", 594 },
			{ 596, "Yes", "No", 596 },
			{ 554, "Skills Interface", "Construction or Hunter", 554 },
			{ 605, "I'm always happy to help a cook in distress.", "I can't right now, Maybe later.", 605 },
			{ 408, "Yes, I would like an easier task.", "No, I want to keep hunting on my current task.", 408 },
			{ 9001, "Teleport me to a random place!", "Leave me here.", 9001 },
			{ 300, "Lock EXP", "Unlock EXP", 300 },
			{ 12, "I need an assignment.", "Err... nothing.", 5 },
			{ 14, "I need another assignment.", "Err... nothing.", 6 },
			{ 15, "Yes I would like to play", "No, sounds too dangerous for me.", 7 },
			{ 16, "I would like to reset my barrows count.", "I would like to fix all my barrows", 8 },
	};

	private static final Object[][] OPTION2_DIALOGUE_ACTION_DIALOGUE_ID = {
			{ 64, "Yes please.", "No thanks.", 14, 64 },
			{ 67, "Yes.", "No.", 15, 67 },
			{ 72, "Yes, follow Mizgog into the cavern.", "No.", 17, 69 },
			{ 76, "Sure, why not?", "Not right now.", 18, 76 },
			{ 78, "Yes, I'm in need of farming supplies.", "No thanks.", 19, 78 },
			{ 80, "Yes!", "No.", 20, 80 },
			{ 82, "Yes.", "No.", 21, 82 },
			{ 83, "Teleport to rock crabs.", "Nevermind.", 22, 83 },
			{ 85, "Sure.", "No thanks.", 23, 85 },
			{ 87, "Yes.", "No thanks.", 24, 87 },
			{ 89, "Yes.", "No thanks.", 25, 89 },
	};

	private static final Object[][] OPTION2_DIALOGUE_ACTION_NEXT_CHAT = {
			{ 2, "Yea! I'm fearless!", "No way! That looks scary!", 1, 0 },
	};

	private static final Object[][] OPTION3_DIALOGUE_ACTION = {
			{ 574, "Lletya", "Tyras Camp", "Elf Camp", 574 },
			{ 578, "Varrock Sewers", "Varrock Castle", "Dark Wizards", 578 },
			{ 479, "Scorpions", "Al-Kharid Warriors", "Bandit Camp", 479 },
			{ 480, "Ice Queen Lair", "Ice Warriors & Ice Giants", "Mithril Dragons", 480 },
			{ 552, "Show me your store.", "I achieved 99 Hunter.", "Never mind", 552 },
			{ 418, "Show me your store.", "I achieved 99 Herblore.", "Never mind", 418 },
			{ 424, "Show me your store.", "I achieved 99 Crafting.", "Never mind", 424 },
			{ 426, "Show me your store.", "I achieved 99 Fletching.", "Never mind", 426 },
			{ 430, "Show me your store.", "I achieved 99 Smithing.", "Never mind", 430 },
			{ 434, "Show me your store.", "I achieved 99 Cooking.", "Never mind", 434 },
			{ 436, "Show me your store.", "I achieved 99 Firemaking.", "Never mind", 436 },
			{ 438, "Show me your store.", "I achieved 99 Woodcutting.", "Never mind", 438 },
			{ 440, "Show me your store.", "I achieved 99 Farming.", "Never mind", 440 },
			{ 443, "Show me your store.", "I achieved 99 Slayer.", "Never mind", 443 },
			{ 441, "Show me your store.", "I achieved 99 Strength.", "Never mind", 441 },
			{ 446, "Show me your store.", "I achieved 99 Attack.", "Never mind", 446 },
			{ 448, "Show me your store.", "I achieved 99 Hitpoints.", "Never mind", 448 },
			{ 450, "Show me your store.", "I achieved 99 Defence.", "Never mind", 450 },
			{ 452, "Show me your store.", "I achieved 99 Prayer.", "Never mind", 452 },
			{ 454, "Show me your store.", "I achieved 99 Ranging.", "Never mind", 454 },
			{ 456, "Show me your store.", "I achieved 99 Magic.", "Never mind", 456 },
			{ 515, "Adventurer", "Pker", "Skiller", 515 },
			{ 29, "Give me 500k for one vote point!", "I would like to open the vote shop.", "Can you open the vote page for me?", 29 },
	};

	private static final Object[][] OPTION3_DIALOGUE_ACTION_DIALOGUE_ID = {
			{ 68, "Duel Arena", "Barrows", "The TzHaar City", 16, 68 },
	};

	private static final Object[][] OPTION3_DIALOGUE_ACTION_DIALOGUE_ID_TELE_ACTION = {
			{ 59, "Port Phasmatys", "Karamja", "Brimhaven", 13, 59, -1 },
	};

	private static final Object[][] OPTION4_DIALOGUE_ACTION = {
			{ 752, "@cr7@<col=8A4B08>Veteran</col>", "@cr8@<col=2880BC>Forums Admin</col>", "Normal Player", "- First Page -", 752 },
			{ 572, "Tree Gnome Stronghold", "Grand Tree", "Swamp", "Treegnome Village", 572 },
			{ 580, "Falador Castle", "Dark Wizards' Tower", "Goblin Village", "Ice Mountain", 580 },
			{ 582, "Lumbridge Swamp", "Goblins", "Cows", "Chickens", 582 },
			{ 584, "Draynor Manor", "Draynor Jail", "Wizards' Tower", "Draynor Sewers", 584 },
			{ 586, "Al-Kharid Bank", "Al-Kharid Castle", "Scorpions + Slash Bash", "Shantay Pass", 586 },
			{ 592, "Tai Bwo Wannai", "Shilo Village", "Kharazi Jungle", "Moss Giant Isle", 592 },
			{ 507, "Combatlevel 3 - 55", "Combatlevel 50 - 100", "Combatlevel 95+", "Never mind.", 507 },
			{ 601, "What's wrong?", "Can you cook me a cake?", "You don't look very happy.", "Nice hat.", 601 },
			{ 500, "Pure", "Berserker Pure", "Tanker", "Master", 500 },
			{ 485, "I would like to buy shots.", "I would like to exchange my points.", "How am I doing right now?", "Never mind.", 485 },
			{ 481, "Brimhaven Dungeon", "Taverley Dungeon", "Fremennik Slayer Dungeon", "Edgeville Dungeon", 481 },
			{ 401, "I want to see the stuff you have for sale.", "I need another assignment!", "Where is the location of my task?", "Err... Never mind.", 401 },
			{ 412, "H.A.M. Camp", "Draynor", "Ardougne", "Menaphos/Sophanem", 412 },
			{ 413, "Essence", "Dwarven Mine", "Shilo Village", "Deep Wild Mine", 413 },
			{ 550, "Show me your store.", "Teleport me to construction.", "I achieved 99 Construction.", "Never mind", 550 },
			{ 416, "Show me your store.", "Teleport me to Gnome Agility Course.", "I achieved 99 Agility.", "Never mind", 416 },
			{ 420, "Show me your store.", "Bring me to another thieving place.", "I achieved 99 Thieving.", "Never mind", 420 },
			{ 422, "Show me your store.", "Bring me to the abyss.", "I achieved 99 Runecrafting.", "Never mind", 422 },
			{ 428, "Show me your store.", "Bring me to another mining place.", "I achieved 99 Mining.", "Never mind", 428 },
			{ 432, "Show me your store.", "Bring me to another fishing place.", "I achieved 99 Fishing.", "Never mind", 432 },
			{ 522, "Easy", "Normal", "Hard", "Extreme (x4 Runescape's)", 522 },
	};

	private static final Object[][] OPTION4_DIALOGUE_ACTION_NEXT_CHAT = {
			{ 8801, "What are you doing?", "Where are you headed?", "Any advice?", "See you around.", 8801, 0 },
	};

	private static final Object[][] OPTION5_DIALOGUE_ACTION = {
			{ 751, "@cr3@<col=ff0000>Donator</col>", "@cr4@<col=0101DF>Super Donator</col>", "@cr5@<col=088A08>Extreme Donator</col>", "@cr6@<col=5F04B4>Respected</col>", "Next ->", 751 },
			{ 556, "Varrock", "Falador", "Lumbridge", "Draynor", "Al-Kharid", 556 },
			{ 558, "Kharidian Desert", "Morytania", "Karamja", "Brimhaven", "Taverley", 558 },
			{ 560, "Musa Point (Karamja)", "Brimhaven", "Crandor", "Entrana", "Miscellania", 560 },
			{ 562, "Fishing Platform", "East Ardougne", "Catherby", "Rellekka", "Waterbirth Island", 562 },
			{ 568, "Barbarian Village", "Troll Stronghold", "Trollweis Mountain", "Burthorpe", "White Wolf Mountain", 568 },
			{ 570, "Fremennik Slayer Dungeon", "Tzhaar Cave + Karamja Dungeon", "Catherby", "Ardougne Zoo", "Under Water", 570 },
			{ 588, "Pollnivneach", "Nardah", "Sophanem", "Bandit Camp", "Uzer", 588 },
			{ 590, "Canifis", "Mort'ton", "Burgh de Rott", "Port Phasmatys", "Experiments", 590 },
			{ 504, "Gu'Tanoth", "Sea Troll Queen + Barrelchest", "Mutant Tarn", "The Inadequacy", "Slash Bash", 504 },
			{ 501, "Tzhaar Cave", "Fishing Trawler", "Castle Wars", "Bounty Hunter", "- First Page -", 501 },
			{ 476, "Firemaking", "Fishing", "Fletching", "Herblore", "Next ->", 476 },
			{ 477, "Mining", "Runecrafting", "Slayer", "Smithing", "Next ->", 477 },
			{ 478, "Thieving", "Woodcutting", "Construction", "Hunter", "Next ->", 478 },
			{ 690, "Strength/Attack", "Prayer", "Defence", "Ranging", "- First Page -", 690 },
			{ 482, "Crandor", "Entrana", "Crash Island", "Musa Point/Karamja", "Rellekka", 482 },
			{ 414, "Al-Kharid", "Shilo Village", "Karamja", "Catherby", "Piscatoris Fishing Colony", 414 },
	};

	private static final Object[][] OPTION5_DIALOGUE_ACTION_DIALOGUE_ID_TELE_ACTION = {
			{ 17, "Air altar", "Mind altar", "Water altar", "Earth altar", "More", 10, 17, -1 },
			{ 18, "Fire altar", "Body altar", "Cosmic altar", "Astral altar", "More", 11, 18, -1 },
			{ 19, "Nature altar", "Law altar", "Death altar", "Blood altar", "More", 12, 19, -1 },
	};

	private OptionDialogues() {
	}

	static void register() {
		for (Object[] row : OPTION2_DIALOGUE_ACTION) {
			final int dialogueId = (Integer) row[0];
			final String option1 = (String) row[1];
			final String option2 = (String) row[2];
			final int dialogueActionValue = (Integer) row[3];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendOption2(option1, option2);
				c.dialogueAction = dialogueActionValue;
			});
		}
		for (Object[] row : OPTION2_DIALOGUE_ACTION_DIALOGUE_ID) {
			final int dialogueId = (Integer) row[0];
			final String option1 = (String) row[1];
			final String option2 = (String) row[2];
			final int dialogueActionValue = (Integer) row[3];
			final int dialogueIdValue = (Integer) row[4];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendOption2(option1, option2);
				c.dialogueAction = dialogueActionValue;
				c.dialogueId = dialogueIdValue;
			});
		}
		for (Object[] row : OPTION2_DIALOGUE_ACTION_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String option1 = (String) row[1];
			final String option2 = (String) row[2];
			final int dialogueActionValue = (Integer) row[3];
			final int nextChatValue = (Integer) row[4];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendOption2(option1, option2);
				c.dialogueAction = dialogueActionValue;
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : OPTION3_DIALOGUE_ACTION) {
			final int dialogueId = (Integer) row[0];
			final String option1 = (String) row[1];
			final String option2 = (String) row[2];
			final String option3 = (String) row[3];
			final int dialogueActionValue = (Integer) row[4];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendOption3(option1, option2, option3);
				c.dialogueAction = dialogueActionValue;
			});
		}
		for (Object[] row : OPTION3_DIALOGUE_ACTION_DIALOGUE_ID) {
			final int dialogueId = (Integer) row[0];
			final String option1 = (String) row[1];
			final String option2 = (String) row[2];
			final String option3 = (String) row[3];
			final int dialogueActionValue = (Integer) row[4];
			final int dialogueIdValue = (Integer) row[5];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendOption3(option1, option2, option3);
				c.dialogueAction = dialogueActionValue;
				c.dialogueId = dialogueIdValue;
			});
		}
		for (Object[] row : OPTION3_DIALOGUE_ACTION_DIALOGUE_ID_TELE_ACTION) {
			final int dialogueId = (Integer) row[0];
			final String option1 = (String) row[1];
			final String option2 = (String) row[2];
			final String option3 = (String) row[3];
			final int dialogueActionValue = (Integer) row[4];
			final int dialogueIdValue = (Integer) row[5];
			final int teleActionValue = (Integer) row[6];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendOption3(option1, option2, option3);
				c.dialogueAction = dialogueActionValue;
				c.dialogueId = dialogueIdValue;
				c.teleAction = teleActionValue;
			});
		}
		for (Object[] row : OPTION4_DIALOGUE_ACTION) {
			final int dialogueId = (Integer) row[0];
			final String option1 = (String) row[1];
			final String option2 = (String) row[2];
			final String option3 = (String) row[3];
			final String option4 = (String) row[4];
			final int dialogueActionValue = (Integer) row[5];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendOption4(option1, option2, option3, option4);
				c.dialogueAction = dialogueActionValue;
			});
		}
		for (Object[] row : OPTION4_DIALOGUE_ACTION_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String option1 = (String) row[1];
			final String option2 = (String) row[2];
			final String option3 = (String) row[3];
			final String option4 = (String) row[4];
			final int dialogueActionValue = (Integer) row[5];
			final int nextChatValue = (Integer) row[6];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendOption4(option1, option2, option3, option4);
				c.dialogueAction = dialogueActionValue;
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : OPTION5_DIALOGUE_ACTION) {
			final int dialogueId = (Integer) row[0];
			final String option1 = (String) row[1];
			final String option2 = (String) row[2];
			final String option3 = (String) row[3];
			final String option4 = (String) row[4];
			final String option5 = (String) row[5];
			final int dialogueActionValue = (Integer) row[6];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendOption5(option1, option2, option3, option4, option5);
				c.dialogueAction = dialogueActionValue;
			});
		}
		for (Object[] row : OPTION5_DIALOGUE_ACTION_DIALOGUE_ID_TELE_ACTION) {
			final int dialogueId = (Integer) row[0];
			final String option1 = (String) row[1];
			final String option2 = (String) row[2];
			final String option3 = (String) row[3];
			final String option4 = (String) row[4];
			final String option5 = (String) row[5];
			final int dialogueActionValue = (Integer) row[6];
			final int dialogueIdValue = (Integer) row[7];
			final int teleActionValue = (Integer) row[8];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendOption5(option1, option2, option3, option4, option5);
				c.dialogueAction = dialogueActionValue;
				c.dialogueId = dialogueIdValue;
				c.teleAction = teleActionValue;
			});
		}
	}

	static Object[][] Option2DialogueAction() {
		final Object[][] copy = new Object[OPTION2_DIALOGUE_ACTION.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = OPTION2_DIALOGUE_ACTION[i].clone();
		return copy;
	}

	static Object[][] Option2DialogueActionDialogueId() {
		final Object[][] copy = new Object[OPTION2_DIALOGUE_ACTION_DIALOGUE_ID.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = OPTION2_DIALOGUE_ACTION_DIALOGUE_ID[i].clone();
		return copy;
	}

	static Object[][] Option2DialogueActionNextChat() {
		final Object[][] copy = new Object[OPTION2_DIALOGUE_ACTION_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = OPTION2_DIALOGUE_ACTION_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] Option3DialogueAction() {
		final Object[][] copy = new Object[OPTION3_DIALOGUE_ACTION.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = OPTION3_DIALOGUE_ACTION[i].clone();
		return copy;
	}

	static Object[][] Option3DialogueActionDialogueId() {
		final Object[][] copy = new Object[OPTION3_DIALOGUE_ACTION_DIALOGUE_ID.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = OPTION3_DIALOGUE_ACTION_DIALOGUE_ID[i].clone();
		return copy;
	}

	static Object[][] Option3DialogueActionDialogueIdTeleAction() {
		final Object[][] copy = new Object[OPTION3_DIALOGUE_ACTION_DIALOGUE_ID_TELE_ACTION.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = OPTION3_DIALOGUE_ACTION_DIALOGUE_ID_TELE_ACTION[i].clone();
		return copy;
	}

	static Object[][] Option4DialogueAction() {
		final Object[][] copy = new Object[OPTION4_DIALOGUE_ACTION.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = OPTION4_DIALOGUE_ACTION[i].clone();
		return copy;
	}

	static Object[][] Option4DialogueActionNextChat() {
		final Object[][] copy = new Object[OPTION4_DIALOGUE_ACTION_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = OPTION4_DIALOGUE_ACTION_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] Option5DialogueAction() {
		final Object[][] copy = new Object[OPTION5_DIALOGUE_ACTION.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = OPTION5_DIALOGUE_ACTION[i].clone();
		return copy;
	}

	static Object[][] Option5DialogueActionDialogueIdTeleAction() {
		final Object[][] copy = new Object[OPTION5_DIALOGUE_ACTION_DIALOGUE_ID_TELE_ACTION.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = OPTION5_DIALOGUE_ACTION_DIALOGUE_ID_TELE_ACTION[i].clone();
		return copy;
	}
}
