package server.game.players.actions.dialogues;

import server.Config;
import server.game.players.DialogueHandler;

/**
 * Data tables for the mechanical statement dialogues lifted out of
 * {@link DialogueHandler#sendDialogues(int, int)}.
 *
 * Each row is { dialogueId, arguments... }; a chat npc argument of -1 means
 * "the npc being talked to" (c.talkingNpc) and any other value is the literal npc
 * id the original switch used. Emote arguments are fixed per table and shown in
 * the table name.
 *
 * Generated by build/purge/gen-dialogue-families.js. Do not edit by hand.
 */
public final class StatementDialogues {

	private static final int TALKING_NPC = -1;

	private static final Object[][] ITEM_CHAT1_NEXT_CHAT = {
			{ 150, "Hello", "Test", 4151, 10, 0 },
	};

	private static final Object[][] STATEMENT1_DIALOGUE_ACTION_NEXT_CHAT = {
			{ 1, "You found a hidden tunnel! Do you want to enter it?", 1, 2 },
	};

	private static final Object[][] STATEMENT1_NEXT_CHAT = {
			{ 62, "This is your first time playing, welcome to "+Config.SERVER_NAME+"!", 458 },
			{ 458, "Use ::help if you want to request staff assistance.", 459 },
			{ 459, "Please speak to the Lumbridge Guide to begin your adventure!", -1 },
			{ 472, "The guide gives you a starter pack by choice.", 515 },
			{ 521, "The guide gives you 4 choices.", 522 },
	};

	private static final Object[][] STATEMENT2_NEXT_CHAT = {
			{ 79, "The ship will take you to the river troll's island.", "Are you sure you want to go?", 80 },
	};

	private static final Object[][] STATEMENT4_NEXT_CHAT = {
			{ 71, "@red@WARNING!", "This cavern contains very dangerous monsters.", "You can only escape by teleporting.", "Do you really want to enter?", 72 },
	};

	private StatementDialogues() {
	}

	static void register() {
		for (Object[] row : ITEM_CHAT1_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final int intArg1 = (Integer) row[3];
			final int intArg2 = (Integer) row[4];
			final int nextChatValue = (Integer) row[5];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendItemChat1(line1, line2, intArg1, intArg2);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : STATEMENT1_DIALOGUE_ACTION_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final int dialogueActionValue = (Integer) row[2];
			final int nextChatValue = (Integer) row[3];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendStatement(line1);
				c.dialogueAction = dialogueActionValue;
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : STATEMENT1_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final int nextChatValue = (Integer) row[2];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendStatement(line1);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : STATEMENT2_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final int nextChatValue = (Integer) row[3];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendStatement2(line1, line2);
				c.nextChat = nextChatValue;
			});
		}
		for (Object[] row : STATEMENT4_NEXT_CHAT) {
			final int dialogueId = (Integer) row[0];
			final String line1 = (String) row[1];
			final String line2 = (String) row[2];
			final String line3 = (String) row[3];
			final String line4 = (String) row[4];
			final int nextChatValue = (Integer) row[5];
			DialogueRegistry.register(dialogueId, (dh, c, id) -> {
				dh.sendStatement4(line1, line2, line3, line4);
				c.nextChat = nextChatValue;
			});
		}
	}

	static Object[][] ItemChat1NextChat() {
		final Object[][] copy = new Object[ITEM_CHAT1_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = ITEM_CHAT1_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] Statement1DialogueActionNextChat() {
		final Object[][] copy = new Object[STATEMENT1_DIALOGUE_ACTION_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = STATEMENT1_DIALOGUE_ACTION_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] Statement1NextChat() {
		final Object[][] copy = new Object[STATEMENT1_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = STATEMENT1_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] Statement2NextChat() {
		final Object[][] copy = new Object[STATEMENT2_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = STATEMENT2_NEXT_CHAT[i].clone();
		return copy;
	}

	static Object[][] Statement4NextChat() {
		final Object[][] copy = new Object[STATEMENT4_NEXT_CHAT.length][];
		for (int i = 0; i < copy.length; i++) copy[i] = STATEMENT4_NEXT_CHAT[i].clone();
		return copy;
	}
}
