<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 2                     */
/* CACHE FILE: Generated: Thu, 09 Mar 2006 18:30:04 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_reputation_2 {

 var $ipsclass;
//===========================================================================
// <ips:reputation:desc:>
//===========================================================================
function reputation($show="",$reputationbit="") {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class='borderwrap'>
	<div class='maintitle'>{$this->ipsclass->lang['tb_reputation']}</div>
	<table class='ipbtable' cellspacing='1'>
		$reputationbit
EOF;
//startif
if ( $show['closewindow'] )
{
$IPBHTML .= <<<EOF
<tr><td class='darkrow1' align='center'><a href='javascript:;' onclick='self.close();'><b>{$this->ipsclass->lang['rep_close']}</b></a></td></tr>
EOF;
}//endif
$IPBHTML .= <<<EOF

	</table>
</div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:reputation_reasonbits:desc:>
//===========================================================================
function reputation_reasonbits($posneg="",$reason="") {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
	<td class='row2' width='1%'><img src='style_images/reputation/reputation_$posneg.gif' border='0' alt='' /></td>
	<td class='row2'>$reason</td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:reputation_yourpost:desc:>
//===========================================================================
function reputation_yourpost($reasonbits="") {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr><td class='darkrow1'>{$this->ipsclass->lang['rep_info']}</td></tr>
<tr>
	<td class='row2'>
	<div class='tablepad'>
EOF;
//startif
if ( $reasonbits )
{
$IPBHTML .= <<<EOF
<fieldset class='fieldset'>
			<legend>{$this->ipsclass->lang['rep_comments']}</legend>
			<table class='ipbtable' cellpadding='0'>
			$reasonbits
			</table>
		</fieldset><br />
EOF;
}//endif
$IPBHTML .= <<<EOF

		<div class='formsubtitle' align='center'><strong>{$this->ipsclass->lang['rep_points']}</strong></div>
	</div>
	</td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:reputationbit:desc:>
//===========================================================================
function reputationbit($show="",$fid="",$pid="",$user="") {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr><td class='darkrow1'>{$this->ipsclass->lang['rep_add']}: <b>$user</b></td></tr>
<tr>
	<td class='row2'>
	<form action='{$this->ipsclass->base_url}' method='post'>	
	<div class='tablepad'>
		<fieldset>
			<legend>{$this->ipsclass->lang['rep_text']}</legend>
			<table class='ipbtable' cellspacing='0'>
			<tr>
				<td>
					<div><label for='rb_reputation_pos'><input type='radio' name='reputation' value='pos' id='rb_reputation_pos' checked='checked' class='radiobutton' style='margin:0px;' /> &nbsp;{$this->ipsclass->lang['rep_approve']}</label></div>
EOF;
//startif
if ( $show['negativerep'] )
{
$IPBHTML .= <<<EOF
<div><label for='rb_reputation_neg'><input type='radio' name='reputation' value='neg' id='rb_reputation_neg' class='radiobutton' style='margin:0px;' /> &nbsp;{$this->ipsclass->lang['rep_disapprove']}</label></div>
EOF;
}//endif
$IPBHTML .= <<<EOF

				</td>
			</tr>
			<tr>
				<td>
					{$this->ipsclass->lang['rep_comment']}:<br />
					<input type='text' size='40' maxlength='250' name='reason' style='margin:0px;' />
				</td>
			</tr>
			</table>
		</fieldset>
	</div>
	<div align='center' style='margin-top:3px;'>
		<input type='hidden' name='act' value='reputation' />
		<input type='hidden' name='do' value='addrep' />
		<input type='hidden' name='fid' value='$fid' />
		<input type='hidden' name='pid' value='$pid' />
		<input type='submit' value="{$this->ipsclass->lang['rep_add']}" class='button' accesskey='s' />
	</div>	
	</form>	
	</td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>